defaults:
  - _self_
  - task: pt
  - local_env: default

# Experiment args
mode: 'pt'
device: gpu
precision: 'bf16'
eval_only: false
predict_only: false
seed: 2137

model:
  klass: gpt
  name: 'gpt2'
  overwrite:
    vocab_size: 50304
  add_config:
    is_bf16: false
    block_size: 1024
    dropout: 0.0
    bias: True
    # mup
    use_mup: true
    output_mult: 1.0
    mup_base_width: 256
    hp_tune_actual_width: 256
    zero_query: true
    zero_emb: true
  checkpoint_path: ''
  random_init: true
  compile: false # Pytorch 2.0

data:
  input_length: 512
  mlm_probability: 0.15
  mean_noise_span_length: 3.0
  num_workers: 2

optim:
  name: adamwscale
  base_lr: 2e-2
  batch_size: 16
  total_steps:  7000 #7000 #65536
  epochs: -1 # If it's > 0 it overwrites total_steps
  warmup_steps: 5000 # 5000
  lr_scheduler: cosine
  weight_decay: 0.0
  grad_clip: 1.0
  grad_acc: 1
  final_cosine: 1e-5

eval:
  every_steps: 100000 # Eval once in the end
  steps: 500

checkpoint:
  every_steps: 100000 # Save checkpoint once in the end

logging:
  neptune: false
  neptune_creds:
    project:
    api_token:
    tags: ''
  every_steps: 100
  grad_l2: true
  weights_l2: true

hydra:
  job:
    chdir: True
